import type { Finding, Signal } from "@vibe/shared";

import type { AnalysisContext } from "../context";

/**
 * Fingerprints left by AI app builders.
 *
 * Like the commit trailers, a hit here is close to ground truth — these artifacts
 * are written by the platform, not by whoever prompted it. A project can of course
 * be exported from Lovable and then developed by hand for months, so this raises
 * the score without asserting the current code is unmodified.
 */

export const WEIGHT = 2.5;

interface PlatformMarker {
  platform: string;
  /** Exact repo-relative paths whose presence identifies the platform. */
  paths?: string[];
  /** Path prefixes/segments. */
  pathPatterns?: RegExp[];
  /** Dependency names that only this platform adds. */
  dependencies?: string[];
  /** Text in README or package.json name. */
  text?: RegExp;
}

const MARKERS: PlatformMarker[] = [
  {
    platform: "Lovable",
    dependencies: ["lovable-tagger"],
    pathPatterns: [/^public\/lovable-uploads\//],
    text: /lovable\.dev|lovable\.app|vite_react_shadcn_ts/i,
  },
  {
    platform: "Bolt.new",
    pathPatterns: [/^\.bolt\//],
    text: /bolt\.new/i,
  },
  {
    platform: "v0 by Vercel",
    text: /Generated by \[?v0\]?|v0\.dev|v0\.app/i,
  },
  {
    platform: "Replit Agent",
    paths: [".replit", "replit.nix"],
    text: /replit\.com\/@|Built on Replit/i,
  },
  {
    platform: "Base44",
    text: /base44\.(app|com)/i,
  },
  {
    platform: "Firebase Studio",
    paths: [".idx/dev.nix"],
  },
];

interface PlatformHit {
  platform: string;
  evidence: string;
}

export function detectPlatforms(ctx: AnalysisContext): PlatformHit[] {
  const hits: PlatformHit[] = [];
  const allPaths = ctx.files.all().map((f) => f.relPath);

  // Only README and package manifests are searched for marketing text, so a
  // passing mention of "v0.dev" inside source code does not trigger a match.
  const textSources = ctx.files
    .all()
    .filter(
      (f) =>
        /^readme(\.[a-z]+)?$/i.test(f.relPath) ||
        f.relPath.endsWith("package.json"),
    );

  for (const marker of MARKERS) {
    for (const path of marker.paths ?? []) {
      if (ctx.files.has(path)) {
        hits.push({ platform: marker.platform, evidence: `\`${path}\` present` });
      }
    }
    for (const pattern of marker.pathPatterns ?? []) {
      const match = allPaths.find((p) => pattern.test(p));
      if (match) {
        hits.push({ platform: marker.platform, evidence: `\`${match}\` present` });
      }
    }
    for (const dep of marker.dependencies ?? []) {
      if (ctx.frameworks.dependencies[dep]) {
        hits.push({
          platform: marker.platform,
          evidence: `depends on \`${dep}\``,
        });
      }
    }
    if (marker.text) {
      for (const file of textSources) {
        if (marker.text.test(file.content)) {
          hits.push({
            platform: marker.platform,
            evidence: `referenced in \`${file.relPath}\``,
          });
          break;
        }
      }
    }
  }

  // One entry per platform, keeping the first (most specific) piece of evidence.
  const seen = new Set<string>();
  return hits.filter((h) => {
    if (seen.has(h.platform)) return false;
    seen.add(h.platform);
    return true;
  });
}

export function platformSignal(ctx: AnalysisContext): Signal {
  const hits = detectPlatforms(ctx);

  return {
    id: "builder-platform",
    value: hits.length > 0 ? 1 : 0,
    weight: WEIGHT,
    available: true,
    evidence: hits.map((h) => `${h.platform}: ${h.evidence}`),
  };
}

export function platformFindings(ctx: AnalysisContext): Finding[] {
  const hits = detectPlatforms(ctx);
  if (hits.length === 0) return [];

  return [
    {
      ruleId: "ai-builder-platform",
      dimension: "provenance",
      severity: "info",
      confidence: "certain",
      source: "builtin",
      title: `Scaffolded by ${hits.map((h) => h.platform).join(", ")}`,
      locations: [],
      data: {
        platforms: hits.map((h) => h.platform),
        evidence: hits.map((h) => h.evidence),
      },
    },
  ];
}
