import type { Signal } from "@vibe/shared";

import { clamp01, unavailable, type AnalysisContext } from "../context";

/**
 * Agent attribution left in commit metadata.
 *
 * Unlike every other signal in this analyzer, a hit here is ground truth rather
 * than a heuristic: the commit itself says an agent wrote it. The scorer treats a
 * positive result as `certain` confidence.
 *
 * Deliberately excluded from calibration tests — if the corpus can be separated
 * by this signal alone, the structural signals have not been shown to work.
 */

interface AgentMarker {
  name: string;
  /** Matched against the full commit message (subject + body). */
  message?: RegExp;
  /** Matched against the author email. */
  email?: RegExp;
}

const AGENT_MARKERS: AgentMarker[] = [
  {
    name: "Claude Code",
    message: /Co-Authored-By:\s*Claude/i,
    email: /noreply@anthropic\.com/i,
  },
  { name: "Claude Code", message: /Generated with \[?Claude Code\]?/i },
  { name: "GitHub Copilot", message: /Co-Authored-By:\s*(GitHub )?Copilot/i },
  { name: "GitHub Copilot", email: /copilot@(users\.noreply\.)?github\.com/i },
  { name: "Cursor", message: /Co-Authored-By:\s*Cursor/i },
  { name: "Cursor", email: /@cursor\.(com|sh)/i },
  { name: "Devin", message: /Co-Authored-By:\s*Devin/i, email: /@cognition(-labs)?\.(ai|com)/i },
  { name: "Aider", message: /^aider:/im },
  { name: "Codex", message: /Co-Authored-By:\s*(OpenAI )?Codex/i },
  { name: "Windsurf", message: /Co-Authored-By:\s*Windsurf/i },
  { name: "Bolt", message: /Co-Authored-By:\s*Bolt/i },
  { name: "Lovable", message: /Co-Authored-By:\s*(Lovable|gpt-engineer)/i },
  { name: "Replit Agent", message: /Replit-Commit-Author:\s*Agent/i },
  { name: "Devlo", message: /Co-Authored-By:\s*devlo/i },
];

export const WEIGHT = 3;

export function agentTrailerSignal(ctx: AnalysisContext): Signal {
  if (!ctx.git.available) {
    return unavailable(
      "agent-trailers",
      WEIGHT,
      ctx.git.unavailableReason ?? "git history unavailable",
    );
  }

  const hitsByAgent = new Map<string, number>();
  let attributedCommits = 0;

  for (const commit of ctx.git.commits) {
    const matched = new Set<string>();
    for (const marker of AGENT_MARKERS) {
      if (marker.message?.test(commit.body)) matched.add(marker.name);
      else if (marker.email?.test(commit.authorEmail)) matched.add(marker.name);
    }
    if (matched.size > 0) attributedCommits++;
    for (const name of matched) {
      hitsByAgent.set(name, (hitsByAgent.get(name) ?? 0) + 1);
    }
  }

  const ratio = clamp01(attributedCommits / ctx.git.commitCount);
  const evidence: string[] = [];

  if (attributedCommits > 0) {
    const agents = [...hitsByAgent.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([name, n]) => `${name} (${n})`);
    evidence.push(
      `${attributedCommits} of ${ctx.git.commitCount} commits carry AI agent attribution`,
      `Agents identified: ${agents.join(", ")}`,
    );
  }

  return {
    id: "agent-trailers",
    value: trailerValue(attributedCommits, ratio),
    weight: WEIGHT,
    available: true,
    evidence,
  };
}

/**
 * Attribution below this share of history means agents *touched* the project,
 * not that the project was generated by them.
 */
const MATERIAL_RATIO = 0.1;

/**
 * Scale with the share of history that carries attribution.
 *
 * This used to saturate at 0.6 on a single attributed commit, on the theory that
 * any attribution is decisive. Measured against real repositories that proved
 * badly wrong: `colinhacks/zod` has 10 agent-attributed commits out of 2,612
 * (0.4%) from drive-by contributors, and scored as though it were substantially
 * agent-written — with `certain` confidence, because this is a ground-truth
 * signal. A long, overwhelmingly human history with a handful of agent commits
 * is a human codebase.
 *
 * Above `MATERIAL_RATIO` the old saturating behaviour is correct and kept.
 */
export function trailerValue(attributedCommits: number, ratio: number): number {
  if (attributedCommits === 0) return 0;
  if (ratio >= MATERIAL_RATIO) return Math.max(0.6, ratio);
  return (ratio / MATERIAL_RATIO) * 0.6;
}

/** Agent names found in history, for the report. Empty when none. */
export function attributedAgents(ctx: AnalysisContext): string[] {
  if (!ctx.git.available) return [];
  const found = new Set<string>();
  for (const commit of ctx.git.commits) {
    for (const marker of AGENT_MARKERS) {
      if (marker.message?.test(commit.body) || marker.email?.test(commit.authorEmail)) {
        found.add(marker.name);
      }
    }
  }
  return [...found].sort();
}
