import type { Finding, Signal } from "@vibe/shared";

import type { AnalysisContext } from "../context";

/**
 * Artifacts left behind by AI tooling, in two families.
 *
 * **Builders** (`kind: "builder"`) are no-code generators — Lovable, Bolt, v0.
 * Their markers say the project was *scaffolded* by a generator, though it may
 * have been developed by hand for months since.
 *
 * **Agents** (`kind: "agent"`) are coding assistants driven from an editor or
 * CLI. Their marker is usually a config file the developer wrote *for* the
 * agent — `CLAUDE.md`, `.cursorrules`, `.github/copilot-instructions.md`. That
 * is arguably the stronger evidence of the two: nobody maintains instructions
 * for a tool they do not use, whereas an export marker can be years stale.
 *
 * Both are close to ground truth, so both emit findings marked `certain` — the
 * file either exists or it does not. They do *not* make the dimension score
 * certain; that is coverage, and finding a config file says nothing about how
 * much of the evidence we managed to gather.
 *
 * They stay separate because they support different claims: the report should
 * not conflate "scaffolded by Lovable" with "developed with Claude Code".
 *
 * One matcher serves both — splitting it would duplicate roughly forty lines,
 * which our own `duplicate-logic` signal would rightly flag.
 */

export const BUILDER_WEIGHT = 2.5;
/**
 * Weighted above the builder markers, and level with commit attribution.
 *
 * A committed agent config is maintained alongside the code, so it implies
 * *ongoing* use. A builder artifact records a one-time export that may be years
 * stale. It is not weighted higher than `agent-trailers`, because a per-commit
 * trailer is direct evidence of who wrote a change, where a config file is
 * evidence of how the project is set up.
 */
export const AGENT_WEIGHT = 3;

type MarkerKind = "builder" | "agent";

interface ToolMarker {
  tool: string;
  kind: MarkerKind;
  /** Exact repo-relative paths whose presence identifies the tool. */
  paths?: string[];
  /** Path prefixes/segments. */
  pathPatterns?: RegExp[];
  /** Dependency names that only this tool adds. */
  dependencies?: string[];
  /** Text in README or package.json name. */
  text?: RegExp;
}

const MARKERS: ToolMarker[] = [
  // --- no-code builders -----------------------------------------------------
  {
    tool: "Lovable",
    kind: "builder",
    dependencies: ["lovable-tagger"],
    pathPatterns: [/^public\/lovable-uploads\//],
    text: /lovable\.dev|lovable\.app|vite_react_shadcn_ts/i,
  },
  {
    tool: "Bolt.new",
    kind: "builder",
    pathPatterns: [/^\.bolt\//],
    text: /bolt\.new/i,
  },
  {
    tool: "v0 by Vercel",
    kind: "builder",
    text: /Generated by \[?v0\]?|v0\.dev|v0\.app/i,
  },
  {
    tool: "Replit Agent",
    kind: "builder",
    paths: [".replit", "replit.nix"],
    text: /replit\.com\/@|Built on Replit/i,
  },
  { tool: "Base44", kind: "builder", text: /base44\.(app|com)/i },
  { tool: "Firebase Studio", kind: "builder", paths: [".idx/dev.nix"] },

  // --- coding agents --------------------------------------------------------
  {
    tool: "Claude Code",
    kind: "agent",
    paths: ["CLAUDE.md", ".claude/settings.json", ".mcp.json"],
    // Nested CLAUDE.md files are common in monorepos, one per package.
    pathPatterns: [/(^|\/)CLAUDE\.md$/, /(^|\/)\.claude\//],
  },
  {
    tool: "Cursor",
    kind: "agent",
    paths: [".cursorrules", ".cursorignore"],
    pathPatterns: [/(^|\/)\.cursor\//],
  },
  {
    tool: "GitHub Copilot",
    kind: "agent",
    paths: [".github/copilot-instructions.md"],
    pathPatterns: [/^\.github\/instructions\/.*\.instructions\.md$/],
  },
  {
    tool: "Windsurf",
    kind: "agent",
    paths: [".windsurfrules"],
    pathPatterns: [/(^|\/)\.windsurf\//],
  },
  {
    tool: "Aider",
    kind: "agent",
    paths: [".aider.conf.yml", ".aider.conf.yaml"],
    pathPatterns: [/(^|\/)\.aider\./],
  },
  { tool: "Cline", kind: "agent", paths: [".clinerules"] },
  { tool: "Continue", kind: "agent", pathPatterns: [/(^|\/)\.continue\//] },
  { tool: "Gemini CLI", kind: "agent", pathPatterns: [/(^|\/)GEMINI\.md$/] },
  { tool: "Junie", kind: "agent", pathPatterns: [/(^|\/)\.junie\//] },
  {
    tool: "SpecStory",
    kind: "agent",
    pathPatterns: [/(^|\/)\.specstory\//],
  },
  {
    // An agent-agnostic convention several tools now read.
    tool: "AGENTS.md convention",
    kind: "agent",
    pathPatterns: [/(^|\/)AGENTS\.md$/],
  },
];

export interface ToolHit {
  tool: string;
  kind: MarkerKind;
  evidence: string;
}

export function detectTooling(ctx: AnalysisContext): ToolHit[] {
  const hits: ToolHit[] = [];
  const allPaths = ctx.files.all().map((f) => f.relPath);

  // Only README and package manifests are searched for marketing text, so a
  // passing mention of "v0.dev" inside source code does not trigger a match.
  const textSources = ctx.files
    .all()
    .filter(
      (f) =>
        /^readme(\.[a-z]+)?$/i.test(f.relPath) ||
        f.relPath.endsWith("package.json"),
    );

  for (const marker of MARKERS) {
    const add = (evidence: string) =>
      hits.push({ tool: marker.tool, kind: marker.kind, evidence });

    for (const path of marker.paths ?? []) {
      if (ctx.files.has(path)) add(`\`${path}\` present`);
    }
    for (const pattern of marker.pathPatterns ?? []) {
      const match = allPaths.find((p) => pattern.test(p));
      if (match) add(`\`${match}\` present`);
    }
    for (const dep of marker.dependencies ?? []) {
      if (ctx.frameworks.dependencies[dep]) add(`depends on \`${dep}\``);
    }
    if (marker.text) {
      const hit = textSources.find((f) => marker.text!.test(f.content));
      if (hit) add(`referenced in \`${hit.relPath}\``);
    }
  }

  // One entry per tool, keeping the first (most specific) piece of evidence.
  const seen = new Set<string>();
  return hits.filter((h) => {
    if (seen.has(h.tool)) return false;
    seen.add(h.tool);
    return true;
  });
}

/** Back-compat alias: builders only. */
export function detectPlatforms(ctx: AnalysisContext): ToolHit[] {
  return detectTooling(ctx).filter((h) => h.kind === "builder");
}

export function platformSignal(ctx: AnalysisContext): Signal {
  const hits = detectPlatforms(ctx);

  return {
    id: "builder-platform",
    value: hits.length > 0 ? 1 : 0,
    weight: BUILDER_WEIGHT,
    available: true,
    evidence: hits.map((h) => `${h.tool}: ${h.evidence}`),
  };
}

/**
 * Coding-agent configuration committed to the repository.
 *
 * Ground truth for "an AI agent was set up to work on this codebase" — a
 * narrower claim than "this code was generated", and the finding wording keeps
 * that distinction. The score treats it as strong evidence because in practice
 * nobody writes and maintains agent instructions for an agent they never run.
 */
export function agentToolingSignal(ctx: AnalysisContext): Signal {
  const hits = detectTooling(ctx).filter((h) => h.kind === "agent");

  return {
    id: "agent-tooling",
    value: hits.length > 0 ? 1 : 0,
    weight: AGENT_WEIGHT,
    available: true,
    evidence: hits.map((h) => `${h.tool}: ${h.evidence}`),
  };
}

export function platformFindings(ctx: AnalysisContext): Finding[] {
  const all = detectTooling(ctx);
  const findings: Finding[] = [];

  const builders = all.filter((h) => h.kind === "builder");
  if (builders.length > 0) {
    findings.push({
      ruleId: "ai-builder-platform",
      dimension: "authorship",
      severity: "info",
      confidence: "certain",
      source: "builtin",
      title: `Scaffolded by ${builders.map((h) => h.tool).join(", ")}`,
      locations: [],
      data: {
        platforms: builders.map((h) => h.tool),
        evidence: builders.map((h) => h.evidence),
      },
    });
  }

  const agents = all.filter((h) => h.kind === "agent");
  if (agents.length > 0) {
    findings.push({
      ruleId: "ai-agent-tooling",
      dimension: "authorship",
      severity: "info",
      confidence: "certain",
      source: "builtin",
      title: `Configured for AI-assisted development with ${agents
        .map((h) => h.tool)
        .join(", ")}`,
      locations: [],
      data: {
        tools: agents.map((h) => h.tool),
        evidence: agents.map((h) => h.evidence),
      },
    });
  }

  return findings;
}
