import type { Finding } from "@vibe/shared";

import { arr, countOf, duration, list, num, str } from "./format";

type Data = Finding["data"];

export interface PersonaTemplate {
  body(data: Data, finding: Finding): string;
  /** Consequence, fix, or cost — whichever this persona needs. */
  detail?(data: Data, finding: Finding): string[];
}

export interface RuleTemplate {
  title(data: Data, finding: Finding): string;
  founder: PersonaTemplate;
  engineer: PersonaTemplate;
  acquirer: PersonaTemplate;
}

/**
 * One template per rule, per persona.
 *
 * Every sentence a reader sees originates here, which is what makes the report
 * auditable: there is no generation step that could assert something the
 * analyzers did not actually measure.
 */
export const RULE_TEMPLATES: Record<string, RuleTemplate> = {
  "ai-authored-commits": {
    title: (d) => `Commit history is attributed to ${list(arr(d, "agents"))}`,
    founder: {
      body: (d) =>
        `The project's own commit history records that ${list(arr(d, "agents"))} wrote part of this code. ` +
        `This is not a guess — the commits say so directly.`,
      detail: () => [
        "This is not a problem by itself. It matters because AI-written code tends to fail in specific ways, which is what the rest of this report checks for.",
      ],
    },
    engineer: {
      body: (d) =>
        `Agent attribution found in commit metadata: ${list(arr(d, "agents"))}. ` +
        `Ground truth, not inference — authorship confidence is reported as certain.`,
    },
    acquirer: {
      body: (d) =>
        `Authorship is documented in version control: ${list(arr(d, "agents"))}. ` +
        `Treat the security findings below as the material risk, not the authorship itself.`,
    },
  },

  "ai-builder-platform": {
    title: (d) => `Scaffolded by ${list(arr(d, "platforms"))}`,
    founder: {
      body: (d) =>
        `This project was built with ${list(arr(d, "platforms"))}. ` +
        `Apps generated by these tools ship quickly but commonly leave gaps around who is allowed to see what.`,
      detail: (d) => [`Evidence: ${list(arr(d, "evidence"))}.`],
    },
    engineer: {
      body: (d) =>
        `Builder artifacts detected: ${list(arr(d, "evidence"))}. ` +
        `The project may have been developed further by hand since export.`,
    },
    acquirer: {
      body: (d) =>
        `Originated from ${list(arr(d, "platforms"))}. ` +
        `Expect little architectural intent and verify the security findings before valuing the codebase.`,
    },
  },

  "ai-agent-tooling": {
    title: (d) => `Set up for AI-assisted development with ${list(arr(d, "tools"))}`,
    founder: {
      body: (d) =>
        `This repository contains configuration written for ${list(arr(d, "tools"))} — ` +
        `instructions telling an AI coding assistant how to work on this codebase.`,
      detail: () => [
        "That means AI tooling was set up here deliberately. It does not tell us which lines it wrote, only that it was part of how this project was built.",
      ],
    },
    engineer: {
      body: (d) =>
        `Agent configuration committed: ${list(arr(d, "evidence"))}. ` +
        `Evidence the tooling was configured, not a claim about any specific line.`,
    },
    acquirer: {
      body: (d) =>
        `Developed with ${list(arr(d, "tools"))}. ` +
        `Weigh the authorship score and any security findings accordingly; the tooling itself is not a defect.`,
    },
  },

  "duplicate-function": {
    title: (d) =>
      `${num(d, "copies")} near-identical copies of the same function`,
    founder: {
      body: (d) =>
        `The same logic has been written ${num(d, "copies")} separate times, under different names ` +
        `(${list(arr(d, "names"))}). Each copy does the same thing.`,
      detail: () => [
        "When one copy needs a fix, the others are easy to miss — so a bug you thought was fixed can keep happening.",
      ],
    },
    engineer: {
      body: (d) =>
        `Type-2 clones (identical structure, differing identifiers): ${list(arr(d, "names"))} ` +
        `across ${countOf(arr(d, "files").length, "file")}.`,
      detail: (d) => [`Extract a shared implementation in ${arr(d, "files")[0] ?? "a shared module"}.`],
    },
    acquirer: {
      body: (d) =>
        `${num(d, "copies")} duplicated implementations of one behaviour. ` +
        `Raises the cost of every future change touching this logic.`,
      detail: (_d, f) => [
        `Consolidation effort: ${duration(f.estimatedFixMinutes ?? 30)}.`,
      ],
    },
  },

  "swallowed-errors": {
    title: (d) => `${num(d, "discarded")} error handlers discard the error`,
    founder: {
      body: (d) =>
        `${num(d, "discarded")} of ${num(d, "total")} places that catch a failure either do nothing ` +
        `with it or only print it. In each case the rest of the app is told the operation succeeded.`,
      detail: () => [
        "This is the shape of bug that is hardest to chase later: something quietly does not work, and there is no error anywhere to explain why.",
      ],
    },
    engineer: {
      body: (d) =>
        `${num(d, "discarded")}/${num(d, "total")} catch blocks are empty or log-only. ` +
        `Failures are suppressed rather than handled.`,
      detail: (d) => {
        const documented = num(d, "documented");
        return documented > 0
          ? [
              `${documented} empty handler(s) carrying an explanatory comment were excluded — a deliberate swallow is not this finding.`,
            ]
          : ["Rethrow, return a result type, or handle the failure."];
      },
    },
    acquirer: {
      body: (d) =>
        `${num(d, "discarded")} of ${num(d, "total")} error paths suppress the failure. ` +
        `Faults surface as incorrect behaviour rather than as errors, which lengthens diagnosis.`,
      detail: (_d, f) => [
        `Remediation: ${duration(f.estimatedFixMinutes ?? 60)}.`,
      ],
    },
  },

  "unused-dependencies": {
    title: (d) => `${countOf(num(d, "count"), "unused dependency", "unused dependencies")}`,
    founder: {
      body: (d) =>
        `Your project installs ${countOf(num(d, "count"), "package")} it never actually uses ` +
        `(${list(arr(d, "packages"))}).`,
      detail: () => [
        "Unused packages still get downloaded and can still carry security vulnerabilities, so they are worth removing.",
      ],
    },
    engineer: {
      body: (d) =>
        `Declared but never imported: ${list(arr(d, "packages"), 8)}.`,
      detail: () => ["Remove from package.json and reinstall to prune the lockfile."],
    },
    acquirer: {
      body: (d) =>
        `${countOf(num(d, "count"), "dependency", "dependencies")} declared but unused — ` +
        `expands the vulnerability surface with no corresponding functionality.`,
      detail: () => [`Cleanup effort: ${duration(10)}.`],
    },
  },
};

/**
 * Used for any rule without a hand-written template.
 *
 * This is load-bearing rather than a safety net: once vendored scanners are wired
 * in, they will emit far more rule IDs than we will ever template by hand, and
 * every one of them still has to read as a sentence.
 */
export const FALLBACK_TEMPLATE: RuleTemplate = {
  title: (_d, f) => f.title,
  founder: {
    body: (_d, f) =>
      `${f.title}. This was flagged as a ${f.severity} issue in your code.`,
    detail: (_d, f) =>
      f.locations.length > 0
        ? [`Found in ${list(f.locations.map((l) => l.file))}.`]
        : [],
  },
  engineer: {
    body: (_d, f) => f.title,
    detail: (_d, f) =>
      f.locations
        .slice(0, 5)
        .map((l) => `${l.file}${l.line ? `:${l.line}` : ""}`),
  },
  acquirer: {
    body: (_d, f) => `${f.title} (severity: ${f.severity}).`,
    detail: (_d, f) =>
      f.estimatedFixMinutes
        ? [`Remediation: ${duration(f.estimatedFixMinutes)}.`]
        : [],
  },
};

/** Signal-level evidence lines are already human-readable; this only tidies them. */
export function evidenceLine(text: string): string {
  return text.endsWith(".") ? text : `${text}.`;
}

export function templateFor(ruleId: string): RuleTemplate {
  return RULE_TEMPLATES[ruleId] ?? FALLBACK_TEMPLATE;
}

/** Exposed so tests can assert every emitted rule has a real template. */
export function templatedRuleIds(): string[] {
  return Object.keys(RULE_TEMPLATES).sort();
}

export { str };
