import type { Dimension } from "./types";

/**
 * Where a score sits against known hand-written code.
 *
 * A number with no reference frame is unreadable. "21 out of 100" tells a
 * reader nothing about whether 21 is ordinary, and the band words only say what
 * *we* call it — not what a normal repository actually scores. The sweep has
 * been measuring exactly that on every run and throwing the answer away.
 *
 * **The corpus is one-sided and the wording that consumes this must stay inside
 * that.** These are twenty well-known, unambiguously hand-written projects. They
 * can show what hand-written code scores; they say nothing about what generated
 * code scores, because there is no labelled generated corpus here. So this
 * supports "most hand-written repositories land around here" and never "you are
 * in the Nth percentile of repositories", which would be a claim about a
 * population we never sampled.
 */
export interface CorpusBaseline {
  /** How many repositories the distribution was measured over. */
  repos: number;
  /** ISO date (YYYY-MM-DD) of the sweep that produced these numbers. */
  measured: string;
  dimensions: Record<
    Dimension,
    {
      median: number;
      /** Nearest-rank, so every figure here is a score some repo actually got. */
      p90: number;
      max: number;
    }
  >;
}

/**
 * Generated by `pnpm sweep --emit-baseline`, not maintained by hand.
 *
 * Re-run it whenever the corpus or a signal changes and paste the output over
 * this. A hand-edited copy drifts silently from the sweep it claims to
 * describe, and the drift is invisible — nothing fails.
 */
export const CORPUS_BASELINE: CorpusBaseline = {
  repos: 20,
  measured: "2026-08-13",
  dimensions: {
    authorship: { median: 5, p90: 21, max: 24 },
    security: { median: 0, p90: 0, max: 0 },
    health: { median: 13, p90: 23, max: 42 },
  },
};

/** Where one score falls relative to the corpus. */
export type CorpusStanding = "at-or-below" | "above" | "beyond";

/**
 * `beyond` means the score exceeds every hand-written repository we measured.
 *
 * That is deliberately not phrased as a verdict. Exceeding the corpus is a fact
 * about twenty repositories, not proof of anything — the corpus is small, and a
 * large legitimate codebase can out-score all of it on duplication alone.
 */
export function corpusStanding(
  dimension: Dimension,
  score: number,
): CorpusStanding {
  const band = CORPUS_BASELINE.dimensions[dimension];
  if (score > band.max) return "beyond";
  if (score > band.p90) return "above";
  return "at-or-below";
}
